#!/usr/bin/env python3
"""Mirror https://aih.github.io/ into this blog as the /aboutme/ page.

Fetches the source page, rewrites its relative asset references to absolute
aih.github.io URLs, adds a canonical link and a "Blog" nav entry, and writes
the result to aboutme/index.html.

aboutme/index.html carries no YAML front matter, so Jekyll copies it verbatim
as a static file and never runs Liquid over the mirrored markup.

Exit codes: 0 success, 1 fetch or parse failed, 2 --check found drift.
"""

import argparse
import re
import sys
import urllib.request
from pathlib import Path

SOURCE_URL = "https://aih.github.io/"
BASE = "https://aih.github.io/"
BLOG_URL = "https://blog.linkedlegislation.org/"
OUTPUT = "aboutme/index.html"

BANNER = (
    "<!-- Generated by scripts/sync_aboutme.py from %s — do not edit by hand.\n"
    "     Edit the source at https://github.com/aih/aih.github.io instead. -->\n"
    % SOURCE_URL
)

# Values that are already absolute, or are not locations at all.
ABSOLUTE = re.compile(r"^(?:[a-z][a-z0-9+.-]*:|//|#)", re.I)


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "aboutme-sync/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read().decode("utf-8")


def absolutize(html):
    """Point relative src/href and og:image paths at the source origin."""

    def link(m):
        attr, quote, value = m.group("attr"), m.group("q"), m.group("v")
        if not value or ABSOLUTE.match(value):
            return m.group(0)
        return f'{attr}={quote}{BASE}{value.lstrip("/")}{quote}'

    html = re.sub(
        r'(?P<attr>\b(?:src|href))=(?P<q>["\'])(?P<v>[^"\']*)(?P=q)', link, html
    )
    # og:image / twitter:image carry bare asset paths in a content attribute.
    html = re.sub(
        r'(?P<attr>\bcontent)=(?P<q>["\'])(?P<v>assets/[^"\']*)(?P=q)', link, html
    )
    return html


def add_canonical(html):
    """Credit the original page so the mirror is not read as duplicate content."""
    tag = f'\n    <link rel="canonical" href="{SOURCE_URL}">'
    html, n = re.subn(r"(</title>)", r"\1" + tag, html, count=1)
    if not n:
        raise SystemExit("no </title> in source page")
    return html


def add_blog_link(html):
    """Give the mirrored page a way back into the blog it is served from."""
    desktop = f'<li><a href="{BLOG_URL}">Blog</a></li>'
    html, n = re.subn(
        r'(<ul class="nav-links">)(.*?)(</ul>)',
        lambda m: m.group(1) + m.group(2) + desktop + m.group(3),
        html,
        count=1,
        flags=re.S,
    )
    if not n:
        print("warning: nav-links list not found, skipping desktop Blog link")

    mobile = f'<a href="{BLOG_URL}">Blog</a>\n      '
    html, n = re.subn(
        r'(<div class="mobile-menu"[^>]*>.*?)(<a href="mailto:)',
        lambda m: m.group(1) + mobile + m.group(2),
        html,
        count=1,
        flags=re.S,
    )
    if not n:
        print("warning: mobile menu not found, skipping mobile Blog link")
    return html


def build(html):
    html = absolutize(html)
    html = add_canonical(html)
    html = add_blog_link(html)
    return re.sub(r"(<!DOCTYPE html>\s*)", r"\1" + BANNER, html, count=1, flags=re.I)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", default=SOURCE_URL, help="page to mirror")
    ap.add_argument("--output", default=OUTPUT, help="path to write")
    ap.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = ap.parse_args()

    try:
        source = fetch(args.source)
    except Exception as exc:
        print(f"error: could not fetch {args.source}: {exc}", file=sys.stderr)
        return 1

    if "</body>" not in source:
        print("error: source page has no </body>; refusing to write", file=sys.stderr)
        return 1

    page = build(source)
    out = Path(args.output)
    current = out.read_text(encoding="utf-8") if out.exists() else None

    if current == page:
        print(f"{out}: up to date")
        return 0

    if args.check:
        print(f"{out}: out of date")
        return 2

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(page, encoding="utf-8")
    print(f"{out}: {'updated' if current else 'created'} ({len(page):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
