name: Build Jekyll Blog and Add to Blog Branch

on:
  push:
    branches:
      - main
env:
  JEKYLL_ENV: production
jobs:
    jenkins-build:
      runs-on: ubuntu-latest
      concurrency:
        group: ${{ github.workflow }}-${{ github.ref }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}

      steps:
          -  uses: actions/checkout@v3

          # Use GitHub Actions' cache to cache dependencies on servers
          - uses: actions/cache@v2
            with:
                path: vendor/bundle
                key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                restore-keys: |
                  ${{ runner.os }}-gems-
          - uses: jerryjvl/jekyll-build-action@v1

          - id: make-script-executable 
            run: chmod +x "${GITHUB_WORKSPACE}/.github/workflows/blog-publish.sh" # make file runnable, might not be necessary
          - id: blog-publish 
            run: "${GITHUB_WORKSPACE}/.github/workflows/blog-publish.sh './blog' ${{ secrets.AWS_BUCKET }} 'blog' '/*' false"